services:
  backend:
    build: server
    restart: always
    depends_on:
      db:
        condition: service_started
        restart: true
    ports:
      - 8080:8080
    env_file: "configs/server.env"
    networks:
      - todolist_network
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - todolist_network
    env_file: "configs/db.env"
    expose:
      - 5432
volumes:
  db-data:
networks:
  todolist_network: